### ISSUE TITLE
4.457 -- odd font at the end of the yellow box in the public view 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#119]
@Otterfan @jessemartinez

**Comment by Otterfan** [comment]
The tool that converts the Word text to HTML interpreted the `<prose>` indicator in that record as an HTML element because it sort of looks like one (e.g. `<body>`, `<article>`). I've made some changes to the importer so that it should be smarter about that in the future.

If you see it again, you can usually fix the problem in the editor by deleting the offending part and re-typing. I'll make a list of all texts currently in the database that potentially have that problem so we can hand-check them.

**Comment by Otterfan** [comment]
There were a number of records with the same problem. I've fixed them.
