### ISSUE TITLE
in the advanced search: searching 'component' vs. 'title'

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#142]
Searching for “Ithaca” as a ‘component’ returns a different number of hits from searching
with “Ithaca” as ‘title’. We need to explain that ‘title’ means the main title of a work. How best
do that? Change the term to ‘main title’? Also, why are we distinguishing the search for a
component title from that of a (main) title?

**Comment by annakijas1** [comment]
On the advanced search page we can add a section that will inform users on how to search the database. Each field can be defined according to your data and you can provide search tips/examples, etc.

**Comment by annakijas1** [comment]
@Otterfan @jessemartinez would it make sense to merge title and component title in the search, rather than have the two separate drop-down fields?  When you do a search in the library catalog or a database for a title it will bring up an article or chapter title from within a journal or book, as long as that title is indexed. I think that would help with the confusion.

**Comment by annakijas1** [comment]
I see this issue is being discussed in issue #164.
