### ISSUE TITLE
a suggestion for the tombstone: 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#156]
Instead of
The Scattered Papers of Penelope: New and Selected Poems
Anghelaki-Rooke, Katerina
Topic author: Anghelaki-Rooke, Katerina

What about something like the following:
Tr. in The Scattered Papers of Penelope: New and Selected Poems (2009) (this would show both that it is a translation [and not a study] and that it is IN this volume, published on which date)
Topic author: Anghelaki-Rooke, Katerina
"Lipiu" (pp. 97-101)
Translator: Van Dyck, Karen (for translations we likely should name the translators on the tombstone – and for studies, we should name their author)

**Comment by annakijas1** [comment]
The tombstone data should be simple, yet descriptive enough so that users can decide whether to click on it and review all of the data for that record.
The "limit your search" filters on the left identify will identify the text type (translation, etc.), as well as topic author.
Would something like this work, items in parenthesis would not be displayed:
(Title) The Scattered Papers of Penelope: New and Selected Poems
(Topic Author) Anghelaki-Rooke, Katerina
(Date of Publication) 2009

The details about translators or other author types, as well as individual components will be visible to the user when they open the full record.

**Comment by annakijas1** [comment]
View more recent request in #194
