### ISSUE TITLE
in advanced search, the "limit your search" column seems to have been lost? 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#165]
@Otterfan @jessemartinez @GreekCommons

**Comment by jessemartinez** [comment]
The advanced search page has been rewritten and has a date range filter. This should be available tomorrow, Tuesday, Apr 24th.

**Comment by GreekCommons** [comment]
Thank you for adding in the date range filter. I see it now, at the left bottom of the results of a simple search.
      What I miss seeing is a date/year as an option among the drop-down boxes of fields in the Advanced Search.

**Comment by GreekCommons** [comment]
P.S. I now have seen the date range filter also on the Advanced Search page. It surprised me, though, coming as an 'afterthought' or separate from the long list of choices in the 'Select' filter. Is it typical to select dates only via a range, *after* the search?

**Comment by jessemartinez** [comment]
I was treating the date range as a separate type of user input than from the rest of the fields, especially since it has the histogram display.

And you have a point that it shouldn't be hidden until after the user makes a query. I'll look into how to integrate date range search with the rest of the input fields, and make it visible at the start of a search.
