### ISSUE TITLE
under 'persons', on the advanced search page, we need a filter to choose the 'person's' function: 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#170]
@Otterfan @jessemartinez @GreekCommons
Author, editor, translator, illustrator, front matter author, back matter author

**Comment by jessemartinez** [comment]
The advanced search page has been rewritten. The "Persons" field has been removed and various person fields have been [added](https://github.com/BCDigSchol/census/blob/development/app/controllers/public/search_controller.rb#L36-L64).

* topic_author
* citation_name
* component_citation_name

Hopefully, this makes sense for this context.

I haven't added anything to search via function like you listed, though.

**Comment by GreekCommons** [comment]
@Otterfan @jessemartinez @GreekCommons
I can appreciate the benefit of having a distinction between ‘Topic author’ and ‘citation name’, but again I’ll need to have it explained why we would want to distinguish ‘component-citation names’ from ‘citation names’, when a user is unlikely to expect (or to need to know) this distinction in advance of his search(es).
     Under the rubric of citation names, we also believe that an optional distinction of the names by function (through a filter) can prove very useful: e.g., find Keeley as translator, or as editor, or as author (i.e. scholar writing a study), etc. (list given in previous comment). Users will want these distinctions as an option. Note: when a Greek creative author has written something akin to a study, we generally list it under his own works and give it the genre of ‘essay’.

**Comment by jessemartinez** [comment]
Consider the placement of citation name and component citation name in the list of fields to search on in the advanced search as an everything-and-the-kitchen-sink approach to showing what it available in the search box! It's not meant to be prescriptive but just as a demo of what's there, and for your feedback.

I'm considering your suggestion on having a filter for the person's function, e.g. translator, editor, author, etc., and need some help visualizing how this works. Do you imagine a separate facet/filter with the function terms that is displayed once the query is made? Or as a separate field in the advanced search drop down? I'm not sure how the latter example would work since it's dependent on there also being a "person" field being searched upon.

**Comment by annakijas1** [comment]
Consider creating an index of all names (from topic author and citation name/role fields) that can be parsed from the data so that users can easily see who they might find in the database. @Otterfan

**Comment by annakijas1** [comment]
This has been implemented. Minor tweaks will occur to public interface.
